config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: 'tasks'

  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks/new', to: 'tasks#submit_new', as: 'submit_new_task'
  
  get 'tasks/edit/:id', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/edit/:id', to: 'tasks#submit_edit', as: 'submit_edited_task'

  get 'tasks/remove/:id', to: 'tasks#remove', as: 'remove_task' 
  
  get 'tasks/toggle-complete/:id', to: 'tasks#toggle_completed', as: 'toggle_completed_task'

  get 'tasks/:id', to: 'tasks#show', as: 'task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def submit_new
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def submit_edit
    Task.update(params[:id], task_params)
    redirect_to tasks_path
  end

  def toggle_completed
    task = Task.find(params[:id])
    task.completed = !task.completed
    task.save
    redirect_to tasks_path
  end

  def remove
    Task.delete(params[:id])
    redirect_to tasks_path
  end

  private

  def task_params
    return params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task, url: url) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <%= f.label :details %>
    <%= f.text_field :details %><br>

    <% if should_show_boolean %>
        <%= f.check_box :completed %><br>
    <% end %>

    <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="banenr">
    <h1>Edit task</h1>
</div>

<div id="index-content" class="container">
    <%= render partial: 'tasks/form', locals: { task: @task, url: submit_edited_task_path(@task.id), should_show_boolean: true } %>
</div>

<div class="footer">
    <%= link_to 'back', tasks_path, class: 'btn btn-grey' %>
</div>

app/views/tasks/index.html.erb
<div class="banner">
    <h1>Tasks</h1>
</div>

<div id="index-content" class="container">
    <ul id="tasks-list">
        <% @tasks.each do |task| %>
            <li class="<%= task.completed ? 'completed' : 'pending' %>">
                <%= link_to toggle_completed_task_path(task.id), title: "toggle complete" do %>
                    <i class="<%= task.completed ? 'fa fa-check-square-o' : 'fa fa-square-o' %>"></i>
                <% end %>
                <%= link_to task.title, task_path(task.id) %>
            </li>
        <% end %>
    </ul>
    
</div>

<div class="footer">
    <div class="container">
        <%= link_to 'add task', new_task_path, class: "btn btn-blue" %>
    </div>
</div>

app/views/tasks/new.html.erb
<div class="banner">
    <h1>Add task</h1>
</div>


<%= render partial: 'tasks/form', locals: { task: @task, url: submit_new_task_path, should_show_boolean: false } %>
<%= link_to 'back', tasks_path, class: 'btn btn-grey' %>

app/views/tasks/show.html.erb
<div class="banner">
    <h1><%= @task.title %></h1>
</div>

<div class="container">
    <p><%= @task.details %></p>
    <p id="task-status" class="<%= @task.completed ? 'color-completed' : 'color-pending' %>"><%= @task.completed ? 'completed' : 'pending' %></p>
    <%= link_to 'edit', edit_task_path, class: 'btn btn-blue' %>
    <%= link_to 'delete', remove_task_path, class: 'btn btn-red' %>
    <%= link_to 'back', tasks_path, class: 'btn btn-grey' %>
</div>